### ISSUE TITLE
Make Live SEO analytics

### ISSUE THREAD

**Issue by QuadropicHQ** [QuadropicHQ/quadropic.com#14]
**Is your feature request related to a problem? Please describe.**
Collect SEO Data and Website Performance Analytics and ping it to Discord
**Describe the solution you'd like**
Collect SEO Data and Website Performance Analytics and ping it to Discord

**Comment by MohamedKamran** [comment]
Will look on it!
Possibly using a curl request from an API might help
Though another approach is to make node js env and then run seo analysis

Discord is operating fully as setted!!!

**Comment by MohamedKamran** [comment]
Made performance tab do check out in the latest PR

**Comment by MohamedKamran** [comment]
progress : echo'd the `lighthouse` performance
The previous performance was inaccurate and slow
Still will integrate `Discord` and figure out a way to attach the `perf` to the PR/Commit
